#spring.application.name=hostel_Casa_Flamingo

#String DB_ADDRESS = "jdbc:postgresql://localhost:5433/";
#    String DB_NAME = "g_49_cars";
#    String DB_USER = "my_user";
#    String DB_PASSWORD = "pos1234";

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hostel_Casa_Flamingo
    username: postgres
    password: paSSword
    driver-class-name: org.postgresql.Driver
  application:
    name: Hostel_Casa_Flamingo

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  servlet:
    context-path: /api