#spring.application.name=hostel_Casa_Flamingo

#String DB_ADDRESS = "jdbc:postgresql://localhost:5433/";
#    String DB_NAME = "g_49_cars";
#    String DB_USER = "my_user";
#    String DB_PASSWORD = "pos1234";

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:hostel_Casa_Flamingo}
    username: ${DB_USERNAME:my_user}
    password: ${DB_PASS:pos1234}
    driver-class-name: org.postgresql.Driver
  application:
    name: Hostel_Casa_Flamingo

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  servlet:
    context-path: /api


key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}