<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Your Registration</title>
</head>
<body>

<h1 style="color: green">Подтверждение регистрации</h1>
<h2>Добрый день, ${name}!</h2>
<p>Для подтверждения регистрации пройдите по следующей ссылке:</p>
<a href="${confirmationLink}">Подтвердить регистрацию</a>
<p>Спасибо, что выбрали наш сервис!</p>

</body>

</html>